// ĐÃ SỬA - CTSW003 dòng 2: REPORT_REQUEST=0, MTA_REPORT_REQUEST=2.
// ĐÃ SỬA LỖI 22: bỏ đọc lại cờ trên đối tượng đang soạn; log chỉ ghi giá trị đã set.
// Chưa xác minh giá trị bên chương trình thu.
package SendIPN;

import com.isode.x400api.AMHS_att;
import com.isode.x400api.MSMessage;
import com.isode.x400api.Recip;
import com.isode.x400api.Session;
import com.isode.x400api.X400_att;
import com.isode.x400api.X400ms;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;

/**
 * Low-level Isode X.400 example using Session, MSMessage, Recip and X400ms.
 */
public final class SendMsgAILowLevelReport {

    private static final int P7_SESSION_TYPE = 0;
    private static final int DR_NO_REPORT = 0;
    private static final int MTA_REPORT = 3;
    private static final int IPN_NO_NOTIFICATION = 0;
    private static final int IPN_NON_RECEIPT_NOTIFICATION = 2;

    private static final String P7_MESSAGE_STORE_PRESENTATION_ADDRESS
            = "\"3001\"/Internet=192.168.22.210+3001";

    private static final String P7_USER_OR_ADDRESS
            = "/CN=VVNBOPTA/OU=VVNB/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static final String P7_USER_PASSWORD = "amhs";

    private static final String RECIPIENT_OR_ADDRESS
            = "/CN=VVTSSWIM/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static final String ATS_PRIORITY = "FF";
    private static final String MESSAGE_TEXT
            = "TEST LOW-LEVEL MESSAGE GENERATED BY SENDMSGAILOW\r\n"
            + "ORIGIN: VVTSMHSA\r\n"
            + "DESTINATION: VVTSMHSA\r\n"
            + "THIS MESSAGE VERIFIES THE ISODE X400MS LOW-LEVEL API.";

    private SendMsgAILowLevelReport() {
    }

    public static void main(String[] args) {
        System.out.println("DA SUA LOI 22 - SendMsgAILowLevelReport - CTSW003 dong 2"
                + " - REPORT_REQUEST=0, MTA_REPORT_REQUEST=2 (cau hinh gui)");
        try {
            submitMessage();
        } catch (X400LowLevelException ex) {
            System.err.println("X.400 operation failed: " + ex.getMessage());
            System.err.println("Native error code: " + ex.getErrorCode());
            System.exit(1);
        }
    }

    private static void submitMessage() throws X400LowLevelException {
        Session session = new Session();
        MSMessage message = new MSMessage();
        boolean sessionOpened = false;
        boolean messageCreated = false;

        try {
            System.out.println("Connecting to P7 Message Store using low-level API...");
            System.out.println("Server    : " + P7_MESSAGE_STORE_PRESENTATION_ADDRESS);
            System.out.println("Mailbox   : " + P7_USER_OR_ADDRESS);
            System.out.println("Recipient : " + RECIPIENT_OR_ADDRESS);

            int status = X400ms.x400_ms_open(
                    P7_SESSION_TYPE,
                    P7_USER_OR_ADDRESS,
                    null,
                    P7_USER_PASSWORD,
                    P7_MESSAGE_STORE_PRESENTATION_ADDRESS,
                    session
            );
            check(session, status, "x400_ms_open");
            sessionOpened = true;
            System.out.println("P7 session opened successfully.");

            status = X400ms.x400_ms_msgnew(
                    session,
                    X400_att.X400_MSG_MESSAGE,
                    message
            );
            check(session, status, "x400_ms_msgnew");
            messageCreated = true;

            buildEnvelope(session, message);
            buildOriginatorAndRecipient(session, message);
            buildBasicAtsContent(session, message);

            status = X400ms.x400_ms_msgsend(message);
            check(session, status, "x400_ms_msgsend");

            String messageId = getMessageString(
                    session,
                    message,
                    X400_att.X400_S_MESSAGE_IDENTIFIER
            );
            String ipmId = getMessageString(
                    session,
                    message,
                    X400_att.X400_S_IPM_IDENTIFIER
            );
            String submissionTime = getMessageString(
                    session,
                    message,
                    X400_att.X400_S_MESSAGE_SUBMISSION_TIME
            );

            System.out.println("Message submitted successfully using low-level API.");
            System.out.println("Message ID      : " + messageId);
            System.out.println("IPM ID          : " + ipmId);
            System.out.println("Submission time : " + submissionTime);
        } finally {
            if (messageCreated) {
                int status = X400ms.x400_ms_msgdel(message, 0);
                if (status != X400_att.X400_E_NOERROR) {
                    printCleanupError(session, "x400_ms_msgdel", status);
                }
            }

            if (sessionOpened) {
                int status = X400ms.x400_ms_close(session);
                if (status == X400_att.X400_E_NOERROR) {
                    System.out.println("P7 session closed.");
                } else {
                    printCleanupError(session, "x400_ms_close", status);
                }
            }
        }
    }

    private static void buildEnvelope(Session session, MSMessage message)
            throws X400LowLevelException {
        addMessageString(
                session,
                message,
                X400_att.X400_S_OR_ADDRESS,
                P7_USER_OR_ADDRESS
        );
        addMessageInt(session, message, X400_att.X400_N_PRIORITY, 0);
        addMessageInt(session, message, X400_att.X400_N_CONTENT_TYPE, 22);
        addMessageInt(session, message, X400_att.X400_N_DISCLOSURE, 1);
        
        
        
        addMessageInt(
                session,
                message,
                X400_att.X400_N_IMPLICIT_CONVERSION_PROHIBITED,
                0
        );
        addMessageInt(
                session,
                message,
                X400_att.X400_N_ALTERNATE_RECIPIENT_ALLOWED,
                1
        );
        addMessageInt(
                session,
                message,
                X400_att.X400_N_CONTENT_RETURN_REQUEST,
                1
        );
        addMessageInt(
                session,
                message,
                X400_att.X400_N_RECIPIENT_REASSIGNMENT_PROHIBITED,
                0
        );
        addMessageInt(
                session,
                message,
                X400_att.X400_N_DL_EXPANSION_PROHIBITED,
                0
        );
        addMessageInt(
                session,
                message,
                X400_att.X400_N_CONVERSION_WITH_LOSS_PROHIBITED,
                0
        );
        addMessageString(
                session,
                message,
                X400_att.X400_S_ORIGINAL_ENCODED_INFORMATION_TYPES,
                "ia5-text"
        );
        
        
        
    }

    private static void buildOriginatorAndRecipient(
            Session session,
            MSMessage message) throws X400LowLevelException {
        addRecipient(
                session,
                message,
                X400_att.X400_ORIGINATOR,
                1,
                P7_USER_OR_ADDRESS,
                DR_NO_REPORT,
                IPN_NO_NOTIFICATION
        );

             addRecipient(
                session,
                message,
                X400_att.X400_RECIP_ENVELOPE,
                2,
                RECIPIENT_OR_ADDRESS,
                DR_NO_REPORT,
                IPN_NON_RECEIPT_NOTIFICATION
        );
    }

    private static void buildBasicAtsContent(Session session, MSMessage message)
            throws X400LowLevelException {
        SimpleDateFormat filingTimeFormat
                = new SimpleDateFormat("ddHHmm", Locale.ENGLISH);
        filingTimeFormat.setTimeZone(TimeZone.getTimeZone("UTC"));

        addMessageInt(session, message, AMHS_att.ATS_N_EXTENDED, 0);
        addMessageString(
                session,
                message,
                AMHS_att.ATS_S_FILING_TIME,
                filingTimeFormat.format(new Date())
        );
        addMessageString(
                session,
                message,
                AMHS_att.ATS_S_PRIORITY_INDICATOR,
                ATS_PRIORITY
        );
        addMessageString(
                session,
                message,
                X400_att.X400_S_ORIGINATORS_REFERENCE,
                "SENDMSGAILOW BASIC ATS TEST"
        );
        addMessageString(session, message, AMHS_att.ATS_S_TEXT, MESSAGE_TEXT);
    }

    private static void addRecipient(
            Session session,
            MSMessage message,
            int recipientType,
            int recipientNumber,
            String address,
            int reportRequest,
            int notificationRequest) throws X400LowLevelException {
        Recip recipient = new Recip();

        int status = X400ms.x400_ms_recipnew(
                message,
                recipientType,
                recipient
        );
        check(session, status, "x400_ms_recipnew");


        
        addRecipientString(
                session,
                recipient,
                X400_att.X400_S_OR_ADDRESS,
                address
        );
        addRecipientInt(
                session,
                recipient,
                X400_att.X400_N_ORIGINAL_RECIPIENT_NUMBER,
                recipientNumber
        );
                addRecipientInt(
                session,
                recipient,
                X400_att.X400_N_MTA_REPORT_REQUEST,
                1
        );
        
        addRecipientInt(
                session,
                recipient,
                X400_att.X400_N_REPORT_REQUEST,
                reportRequest
        );
        
        addRecipientInt(
                session,
                recipient,
                X400_att.X400_N_NOTIFICATION_REQUEST,
                notificationRequest
        );
        if (recipientType == X400_att.X400_RECIP_STANDARD) {
            // Getters returned error 22 on this outgoing P7 object.
            // Successful setters do not prove the values received downstream.
            System.out.println("CTSW003 row 2 - setter calls succeeded, recipient: " + address);
            System.out.println("Requested X400_N_REPORT_REQUEST=" + reportRequest
                    + ", X400_N_MTA_REPORT_REQUEST=" + MTA_REPORT
                    + " (not read back; verify at receiver)");
        }
    }

    private static void addMessageString(
            Session session,
            MSMessage message,
            int attribute,
            String value) throws X400LowLevelException {
        int status = X400ms.x400_ms_msgaddstrparam(
                message,
                attribute,
                value,
                -1
        );
        check(session, status, "x400_ms_msgaddstrparam(" + attribute + ")");
    }

    private static void addMessageInt(
            Session session,
            MSMessage message,
            int attribute,
            int value) throws X400LowLevelException {
        int status = X400ms.x400_ms_msgaddintparam(message, attribute, value);
        check(session, status, "x400_ms_msgaddintparam(" + attribute + ")");
    }

    private static void addRecipientString(
            Session session,
            Recip recipient,
            int attribute,
            String value) throws X400LowLevelException {
        int status = X400ms.x400_ms_recipaddstrparam(
                recipient,
                attribute,
                value,
                -1
        );
        check(session, status, "x400_ms_recipaddstrparam(" + attribute + ")");
    }

    private static void addRecipientInt(
            Session session,
            Recip recipient,
            int attribute,
            int value) throws X400LowLevelException {
        int status = X400ms.x400_ms_recipaddintparam(
                recipient,
                attribute,
                value
        );
        check(session, status, "x400_ms_recipaddintparam(" + attribute + ")");
    }

    private static String getMessageString(
            Session session,
            MSMessage message,
            int attribute) throws X400LowLevelException {
        StringBuffer value = new StringBuffer();
        int status = X400ms.x400_ms_msggetstrparam(message, attribute, value);

        if (status == X400_att.X400_E_NO_VALUE) {
            return null;
        }

        check(session, status, "x400_ms_msggetstrparam(" + attribute + ")");
        return value.toString();
    }

    private static void check(Session session, int status, String operation)
            throws X400LowLevelException {
        if (status == X400_att.X400_E_NOERROR) {
            return;
        }

        String detail = X400ms.x400_ms_get_string_error(session, status);
        throw new X400LowLevelException(operation + ": " + detail, status);
    }

    private static void printCleanupError(
            Session session,
            String operation,
            int status) {
        String detail = X400ms.x400_ms_get_string_error(session, status);
        System.err.println(operation + " failed: " + detail + " (" + status + ")");
    }

    private static final class X400LowLevelException extends Exception {

        private final int errorCode;

        private X400LowLevelException(String message, int errorCode) {
            super(message);
            this.errorCode = errorCode;
        }

        private int getErrorCode() {
            return errorCode;
        }
    }
}
