package SendIPN;

import com.isode.x400.highlevel.P7BindSession;
import com.isode.x400.highlevel.X400APIException;
import com.isode.x400.highlevel.X400Msg;
import com.isode.x400api.AMHS_att;
import com.isode.x400api.X400_att;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;

/**
 * Standalone example for submitting a basic ATS message through an Isode P7
 * Message Store. Connection values are intentionally hard-coded for testing.
 */
public final class SendMsgAIHiLevel {

    private static final String P7_MESSAGE_STORE_PRESENTATION_ADDRESS
            = "\"3001\"/Internet=192.168.22.186+3001";

    private static final String P7_USER_OR_ADDRESS
            = "/CN=VVTSUKNN/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static final String P7_USER_PASSWORD = "amhs";

    private static final String RECIPIENT_OR_ADDRESS
            = "/CN=VVTSOPTA/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static final String ATS_PRIORITY = "FF";
    private static final String MESSAGE_TEXT
            = "TEST MESSAGE GENERATED BY SENDMSGAI\r\n"
            + "ORIGIN: VVTSMHSA\r\n"
            + "DESTINATION: VVTSMHSA\r\n"
            + "THIS MESSAGE IS USED TO VERIFY THE ISODE X.400 P7 CONNECTION.";

    private SendMsgAIHiLevel() {
    }

    public static void main(String[] args) {
        P7BindSession session = new P7BindSession(
                P7_MESSAGE_STORE_PRESENTATION_ADDRESS,
                P7_USER_OR_ADDRESS,
                P7_USER_PASSWORD,
                false
        );

        X400Msg message = null;

        try {
            System.out.println("Connecting to P7 Message Store...");
            System.out.println("Server    : " + P7_MESSAGE_STORE_PRESENTATION_ADDRESS);
            System.out.println("Mailbox   : " + P7_USER_OR_ADDRESS);
            System.out.println("Recipient : " + RECIPIENT_OR_ADDRESS);

            session.bind();
            System.out.println("P7 bind successful.");

            // The high-level constructor creates the native message. Do not call
            // X400ms.x400_ms_msgnew() again for this object.
            message = new X400Msg(session);

            buildBasicAtsMessage(message);

            // High-level sendMsg() calls X400ms/native code and converts native
            // error codes into X400APIException.
            message.sendMsg(session);

            System.out.println("Message submitted successfully.");
            System.out.println("Message ID      : " + message.getMessageIdentifier());
            System.out.println("IPM ID          : " + message.getMessageIPMIdentifier());
            System.out.println("Submission time : " + message.getSubmissionTime());
        } catch (X400APIException ex) {
            System.err.println("X.400 operation failed: " + ex.getMessage());
            System.err.println("Native error code: " + ex.getNativeErrorCode());
            System.err.println("Native error text: " + ex.getNativeErrorString());
            ex.printStackTrace(System.err);
        } finally {
            releaseMessage(message);
            unbind(session);
        }
    }

    private static void buildBasicAtsMessage(X400Msg message)
            throws X400APIException {
        SimpleDateFormat filingTimeFormat
                = new SimpleDateFormat("ddHHmm", Locale.ENGLISH);
        filingTimeFormat.setTimeZone(TimeZone.getTimeZone("UTC"));

        // setFrom() creates the originator through the supported high-level API.
        message.setFrom(P7_USER_OR_ADDRESS);

        // setTo() creates the recipient and sets its report/IPN attributes.
        message.setTo(
                RECIPIENT_OR_ADDRESS,
                X400Msg.DR_Request.DR_NON_DELIVERY_REPORT,
                X400Msg.IPN_NON_RECEIPT_NOTIFICATION
        );

        
        
        message.setPriority(X400Msg.X400_Priority.NORMAL_PRIORITY);
        message.setIntParam(AMHS_att.ATS_N_EXTENDED, 0);
        message.setStringparam(
                AMHS_att.ATS_S_FILING_TIME,
                filingTimeFormat.format(new Date())
        );
        message.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, ATS_PRIORITY);
        message.setStringparam(
                X400_att.X400_S_ORIGINATORS_REFERENCE,
                "SENDMSGAI BASIC ATS TEST"
        );
        message.setIntParam(X400_att.X400_N_CONTENT_TYPE, 22);
        message.setStringparam(AMHS_att.ATS_S_TEXT, MESSAGE_TEXT);
    }

    private static void releaseMessage(X400Msg message) {
        if (message == null) {
            return;
        }

        try {
            message.delete(true);
        } catch (X400APIException ex) {
            System.err.println("Cannot release X.400 message: " + ex.getMessage());
        }
    }

    private static void unbind(P7BindSession session) {
        if (session == null || !session.isBound()) {
            return;
        }

        try {
            session.unbind();
            System.out.println("P7 session closed.");
        } catch (X400APIException ex) {
            System.err.println("Cannot unbind P7 session: " + ex.getMessage());
        }
    }
}
