package javaapplication1;


/* 
 * Copyright (c) 2008-2010, Isode Limited, London, England.
 * All rights reserved.
 * 
 * Acquisition and use of this software and related materials for any
 * purpose requires a written licence agreement from Isode Limited,
 * or a written licence from an organisation licenced by Isode Limited
 * to grant such a licence.
 */
import com.isode.x400.highlevel.BodypartGeneralText;
import com.isode.x400.highlevel.BodypartIA5Text;
import com.isode.x400.highlevel.P3BindSession;
import com.isode.x400.highlevel.P7BindSession;
import com.isode.x400.highlevel.X400Msg;
import com.isode.x400.highlevel.X400APIException;
import com.isode.x400.highlevel.X400Msg.X400_Priority;
import com.isode.x400api.AMHS_att;
import com.isode.x400api.BodyPart;
import com.isode.x400api.X400;
import com.isode.x400api.X400_att;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Test program that connects to either an MTA's P3 channel or to a P7 Message
 * Store, and submits a test message to itself.
 *
 */
public class basicGeneralText {

    private static String p7_message_store_presentation_address = "\"3001\"/URI+0000+URL+itot://192.168.22.186:3001";
    //private static String p7_message_store_presentation_address = "\"3001\"/Internet=mts1.amhs+3001";
    //private static String p7_user_or_address = "/OU=VVTSOPTS/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
    private static String p7_user_or_address = "/CN=VVTSMHSA/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    private static String p7_user_password = "amhs";

    private static String recipient_or_address = "/CN=VVTSMHSA/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    /*
    private static String primary1 = "/OU=VVTSMHSA/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
    private static String primary2 = "/OU=VVTSOPTA/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";

    private static String cc1 = "/OU=VVTSMHSB/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
    private static String cc2 = "/OU=VVTSOPTB/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";

    private static String bcc1 = "/OU=VVTSMHSC/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
    private static String bcc2 = "/OU=VVTSOPTC/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
     */
//    private static String primary1 = "/CN=WSSSMHSA/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
//    private static String primary2 = "/CN=WSSSFTNA/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
//    private static String cc1 = "/OU=VVTSOPTD/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
    //private static String cc2 = "/CN=WSSSFTNB/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
//    private static String bcc1 = "/OU=VVTSOPTD/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
    // private static String bcc2 = "/CN=WSSSFTNC/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
    private static String primary1 = "/OU=VVTSOPTA/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
//    private static String primary2 = "/OU=VVTSOPTB/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static String cc1 = "/OU=VVTSOPTC/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
//    private static String cc2 = "/OU=VVTSOPTD/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static String bcc1 = "/OU=VVTSOPTD/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
//    private static String bcc2 = "/OU=VVTSOPTF/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static String subject = "ATTECH BASIC + GENERAL TEXT";
    private static String content = "BASIC + GENERAL TEXT";

    private static String from = "/CN=VVTSMHSA/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static P3BindSession bind_session;

    private static P7BindSession connection;

    
    public static void SendNormalMessage() {
        // Since the bind was successful, create a new message object using the 
        // session object that we just created
        X400Msg x400msg = new X400Msg(bind_session);

        // Request an IPN (InterPersonal Notification)
        // These are often known as Read Receipts, and are sent by the receiving user agent
        // when the message is read from the mailbox.
        //
        // In the case below, a notification is requested in both cases, when messages are
        // read and when messages are not read. 
        // If you don't need the positive notification, just remove it. 
        //int ipn_request = X400Msg.IPN_NON_RECEIPT_NOTIFICATION;
        try {
            // Send the message to itself.
            //
            // Request a delivery report (DR), that is, a message generated by the X.400 MTA that contains 
            // information about the delivery of the message. 
            // In this case below, X400Msg.Delivery_Report.DR_DELIVERY_REPORT means that reports will be generated both 
            // when the message is delivered and when it's not delivered.
            // If you don't want positive DRs, use DR_NON_DELIVERY_REPORT or DR_NO_REPORT
            //x400msg.setTo(recipient_or_address, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, ipn_request);
            
           // x400msg.setIntParam(AMHS_att.ATS_N_EXTENDED, 0);
            
            // Set the subject of the message
            x400msg.setSubject(subject);

            // X.400 messages need a message identifier, that will allow us to correlate 
            // DRs (delivery reports) and IPNs (Inter-Personal Notifications) 
            // This value can be assigned here, or it can be left empty, and a random value
            // will be assigned by the API. This value can be read later with getMessageIPMIdentifier()
            //String msg_id = Long.toString((new Date()).getTime()) + "*";
            //x400msg.setMessageIPMIdentifier(msg_id);
            // Set the MTS Priority
            x400msg.setPriority(X400_Priority.NORMAL_PRIORITY);
            
            

            // Set the content, in this case a simple IA5 text bodypart
            //x400msg.setTextBody("This is the body of the test message");
            // Set an optional X.411 Security Label for the message. 
            // There are four ways to add a security label: as a file with a BER encoded byte array,
            // a file with an XML encoded string, an XML encoded String, or a JRSecurityLabel object
            //x400msg.addSecurityLabelAsBER("/opt/isode/share/x400sdk/example/c/x411seclabel.ber");
            //x400msg.addSecurityLabelAsXMLFileName("/opt/isode/share/security-label/example-data/genser-test/lConfidential.xml");
            // Add another File Transfer bodypart
            //These attributes map to different X400 Attributes depending on the environment. 
            
            //Note that if you are using the basic message service (i.e. ATS_N_EXTENDED is not set, or is set to FALSE) 
            //you must supply all of the mandatory ATS attributes - 
            //ATS-S_PRIORITY_INDICATOR, 
            //ATS_S_FILING_TIME and 
            // ATS_S_TEXT as a set. 
            
            //SimpleDateFormat formatter2 = new SimpleDateFormat("yyMMddHHmmssZ", new Locale("en"));
            SimpleDateFormat formatter2 = new SimpleDateFormat("ddHHmm", new Locale("en"));
            Date now = new Date();
            System.out.println("Generalized Time Basic= " + formatter2.format(now));
            
           // x400msg.setStringparam(X400_att.X400_S_AUTHORIZATION_TIME, formatter2.format(now));
           
           //x400msg.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, "FF"); 
            //400msg.setIntParam(X400_att.X400_N_PRIORITY,57);
            
            // x400msg.setPriority(X400_Priority.NORMAL_PRIORITY);
          //  x400msg.setIntParam(X400_att.X400_N_PRECEDENCE,57);
           //  setIntParam(message, X400_att.X400_N_PRECEDENCE, preference);      // IHE 2
             
            x400msg.setFrom(from);
            String to = "/CN=VVTSMHSA/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
            x400msg.setTo(to, X400Msg.DR_Request.DR_NO_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

  
               
            x400msg.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, "FF");
            x400msg.setStringparam(AMHS_att.ATS_S_FILING_TIME, formatter2.format(now));
            //x400msg.setStringparam(X400_att.X400_S_ORIGINATORS_REFERENCE, "MY BASIC REFERENCE OHI");
                        
             
            String text;
            text = "TEST POT501/TC001";
            x400msg.setStringparam(AMHS_att.ATS_S_TEXT, "IA 5 TEST");   // TÉT OK
            
            
            
            //x400msg.setIntParam(X400_att.X400_S_SUPPLEMENTARY_INFO);
            //x400msg.setStringparam(X400_att.X400_S_SUPPLEMENTARY_INFO, "");

            // x400msg.setStringparam(AMHS_att.ATS_S_TEXT, content);
            
            // Add a General Text bodypart Mode 1
            /*
            BodypartGeneralText gt1 = new BodypartGeneralText(true, "1 6");
            gt1.setTextContent("GENERAL TEXT TEST");
            */
            
            // Add a General Text bodypart Mode 2
            
            SimpleDateFormat formatter1 = new SimpleDateFormat("yyMMddHHmmssZ", new Locale("en"));
            /*
            x400msg.setStringparam(X400_att.X400_S_AUTHORIZATION_TIME, formatter1.format(now));
            x400msg.setStringparam(X400_att.X400_S_ORIGINATORS_REFERENCE, "MY BASIC REFERENCE OHI");
            x400msg.setIntParam( X400_att.X400_N_PRECEDENCE, 57); 
            */
           
            x400msg.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, "FF");
            x400msg.setStringparam(AMHS_att.ATS_S_FILING_TIME, formatter2.format(now));
            String msgText = "BASIC GENERAL";
            x400msg.setStringparam(AMHS_att.ATS_S_TEXT, msgText);
      
       
            //BodypartGeneralText gt1 = new BodypartGeneralText("1 6",msgText, true);
            //BodyPart bp = gt1.getBodypartObject();

/*            
            X400.x400_bodypartaddstrparam(bp, X400_att.X400_S_AUTHORIZATION_TIME, formatter1.format(now), 0);
            X400.x400_bodypartaddstrparam(bp, X400_att.X400_S_ORIGINATORS_REFERENCE, "MY BASIC REFERENCE OHI", 0);
            X400.x400_bodypartaddintparam(bp,X400_att.X400_N_PRECEDENCE, 57);
                         
            //int status = com.isode.x400api.X400ms.x400_ms_msgaddbodypart(x400msg, gt1);
            x400msg.addBodypart(gt1);
*/            
            String ipm_id = x400msg.getMessageIPMIdentifier();
           // x400msg.setIntParam(X400_att.X400_T_IA5TEXT);
            x400msg.setStringparam(X400_att.X400_S_GENERAL_TEXT_CHARSETS, "1 6");
            
            
            
           x400msg.sendMsg(bind_session);
           final String msg_sub_id = x400msg.getMessageIdentifier();
            final String msg_st = x400msg.getSubmissionTime();

            System.out.println("Message submitted.\nMessage Submission ID: "
                    + "\nIPM ID: " + ipm_id + "\nSubmission time: " + msg_st);

        } catch (X400APIException e1) {
           
            e1.printStackTrace();
            System.out.println("Exception code = " + e1.getNativeErrorCode());

        }
    }

    public static void run() {
        System.out.println("Connecting to the P7 Message Store... ");

        // Create a new P7 bind session object with the session values necessary for the bind
        connection = new P7BindSession(p7_message_store_presentation_address,
                p7_user_or_address, p7_user_password);

        // Bind to the P7 Message Store
        try {
            connection.bind();
        } catch (X400APIException e) {
            System.exit(1);
        }

        bind_session = connection;

        
        SendNormalMessage();
      
        try {
            bind_session.unbind();
        } catch (X400APIException ex) {
            Logger.getLogger(SendX400MailS.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static void main(String[] args) {


        run();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(basicGeneralText.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
