
/* 
 * Copyright (c) 2008-2010, Isode Limited, London, England.
 * All rights reserved.
 * 
 * Acquisition and use of this software and related materials for any
 * purpose requires a written licence agreement from Isode Limited,
 * or a written licence from an organisation licenced by Isode Limited
 * to grant such a licence.
 */
package javaapplication1;

import com.isode.x400.highlevel.BodypartFTBP;
import com.isode.x400.highlevel.BodypartGeneralText;
import com.isode.x400.highlevel.BodypartIA5Text;
import com.isode.x400.highlevel.P3BindSession;
import com.isode.x400.highlevel.P7BindSession;
import com.isode.x400.highlevel.X400Msg;
import com.isode.x400.highlevel.X400APIException;
import com.isode.x400.highlevel.X400Msg.X400_Priority;
import com.isode.x400api.AMHS_att;
import com.isode.x400api.X400_att;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Test program that connects to either an MTA's P3 channel or to a P7 Message
 * Store, and submits a test message to itself.
 *
 */
public class SendX400Mail_extend {

    private static String p7_message_store_presentation_address = "\"3001\"/URI+0000+URL+itot://192.168.22.186:3001";
    //private static String p7_message_store_presentation_address = "\"3001\"/Internet=10.65.101.102+3001";
    private static String p7_user_or_address = "/CN=VVTSOPTB/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    private static String p7_user_password = "amhs";

    private static String recipient_or_address = "/CN=VVTSZPZX/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    /*
    private static String primary1 = "/OU=VVTSMHSA/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
    private static String primary2 = "/OU=VVTSOPTA/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";

    private static String cc1 = "/OU=VVTSMHSB/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
    private static String cc2 = "/OU=VVTSOPTB/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";

    private static String bcc1 = "/OU=VVTSMHSC/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
    
    private static String bcc2 = "/OU=VVTSOPTC/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
     */
    private static String primary1 = "/CN=WSSSMHSA/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
    private static String primary2 = "/CN=WSSSFTNA/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
    private static String cc1 = "/CN=WSSSMHSB/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
    private static String cc2 = "/CN=WSSSFTNB/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
    private static String bcc1 = "/CN=WSSSMHSC/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
    private static String bcc2 = "/CN=WSSSFTNC/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";

    /*
    private static String primary1 = "/OU=VVTSOPTA/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    private static String primary2 = "/OU=VVTSOPTB/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static String cc1 = "/OU=VVTSOPTC/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    private static String cc2 = "/OU=VVTSOPTD/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static String bcc1 = "/OU=VVTSOPTE/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    private static String bcc2 = "/OU=VVTSOPTF/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    
     */
    private static String subject = "TEST IT501/TC05";
    private static String content = "TRAN DUC TEST FROM TOOLS CHUYEN MAY ";

    private static String from = "/CN=VVTSOPTA/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static P3BindSession bind_session;

    private static P7BindSession connection;

    public static void SendTOCC() {

        // Since the bind was successful, create a new message object using the 
        // session object that we just created
        X400Msg x400msg = new X400Msg(bind_session);

        // Request an IPN (InterPersonal Notification)
        // These are often known as Read Receipts, and are sent by the receiving user agent
        // when the message is read from the mailbox.
        //
        // In the case below, a notification is requested in both cases, when messages are
        // read and when messages are not read. 
        // If you don't need the positive notification, just remove it. 
        int ipn_request = X400Msg.IPN_NON_RECEIPT_NOTIFICATION;

        try {
            // Send the message to itself.
            //
            // Request a delivery report (DR), that is, a message generated by the X.400 MTA that contains 
            // information about the delivery of the message. 
            // In this case below, X400Msg.Delivery_Report.DR_DELIVERY_REPORT means that reports will be generated both 
            // when the message is delivered and when it's not delivered.
            // If you don't want positive DRs, use DR_NON_DELIVERY_REPORT or DR_NO_REPORT
            //x400msg.setTo(recipient_or_address, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, ipn_request);

            // Set the subject of the message
            x400msg.setSubject(subject);

            // X.400 messages need a message identifier, that will allow us to correlate 
            // DRs (delivery reports) and IPNs (Inter-Personal Notifications) 
            // This value can be assigned here, or it can be left empty, and a random value
            // will be assigned by the API. This value can be read later with getMessageIPMIdentifier()
            //String msg_id = Long.toString((new Date()).getTime()) + "*";
            //x400msg.setMessageIPMIdentifier(msg_id);
            // Set the MTS Priority
            x400msg.setPriority(X400_Priority.NORMAL_PRIORITY);

            // Set the content, in this case a simple IA5 text bodypart
            //x400msg.setTextBody("This is the body of the test message");
            // Set an optional X.411 Security Label for the message. 
            // There are four ways to add a security label: as a file with a BER encoded byte array,
            // a file with an XML encoded string, an XML encoded String, or a JRSecurityLabel object
            //x400msg.addSecurityLabelAsBER("/opt/isode/share/x400sdk/example/c/x411seclabel.ber");
            //x400msg.addSecurityLabelAsXMLFileName("/opt/isode/share/security-label/example-data/genser-test/lConfidential.xml");
            // Add another File Transfer bodypart
            //These attributes map to different X400 Attributes depending on the environment. Note that if you are using the basic message service (i.e. ATS_N_EXTENDED is not set, or is set to FALSE) you must supply all of the mandatory ATS attributes - 
            //ATS-S_PRIORITY_INDICATOR, 
            //ATS_S_FILING_TIME and 
            // ATS_S_TEXT as a set. 
            SimpleDateFormat formatter2 = new SimpleDateFormat("ddHHmm", new Locale("en"));
            Date now = new Date();
            System.out.println("Generalized Time Basic= " + formatter2.format(now));
            //atsMessage.setStringparam(X400_att.X400_S_AUTHORIZATION_TIME, formatter2.format(now));
            
            x400msg.setStringparam(AMHS_att.ATS_S_FILING_TIME, formatter2.format(now));
            x400msg.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, "FF");
            x400msg.setIntParam(AMHS_att.ATS_N_EXTENDED, 0);
            x400msg.setIntParam(X400_att.X400_N_CONTENT_TYPE, 22);
            x400msg.setStringparam(AMHS_att.ATS_S_TEXT, content);

            //           x400msg.setStringparam(AMHS_att.ATS_S_TEXT, content);
            // Add a General Text bodypart
            //BodypartGeneralText gt1 = new BodypartGeneralText(true, "");
            //gt1.setContentFromFile("/etc/hosts");
            //x400msg.addBodypart(gt1);
            // Add a File Transfer bodypart
            //BodypartFTBP ftbp = new BodypartFTBP("/bin/ls");
            //ftbp.setApplicationReferenceOID("2.16.840.1.113694.2.2.1.1");
            //x400msg.addBodypart(ftbp);
            // Set the content type 
            // If a Message IPM Identifier wasn't assigned, read the value that was calculated
            String ipm_id = x400msg.getMessageIPMIdentifier();

            x400msg.setFrom(from);

            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC & ~  X400_att.X400_RECIP_BCC, bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_PRIMARY, to, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_CC, cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC , bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC , bccc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //
            // x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingPrimaryRecipient(to, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingPrimaryRecipient(to1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingCopyRecipient(cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingCopyRecipient(cc1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingBlindCopyRecipient(bcc,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            // Send the message to the Message Store
            //x400msg.sendMsg(bind_session);
            x400msg.setTo(primary1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setTo(primary2, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setCc(cc1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setCc(cc2, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

            x400msg.sendMsg(bind_session);

            // Unbind cleanly from the Message Store
            // The message was correctly submitted to the Message Store
            // Retrieve the message submission ID (assigned by the MTA) and the submission time
            final String msg_sub_id = x400msg.getMessageIdentifier();
            final String msg_st = x400msg.getSubmissionTime();

            System.out.println("Message submitted.\nMessage Submission ID: "
                    + msg_sub_id + "\nIPM ID: " + ipm_id + "\nSubmission time: " + msg_st);

        } catch (X400APIException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
            System.out.println("Exception code = " + e1.getNativeErrorCode());
//            try {
//                bind_session.unbind();
//            } catch (X400APIException e) {
//            }
//            System.exit(1);
        }
    }

    public static void SendBCC(String bcc_address) {

        // Since the bind was successful, create a new message object using the 
        // session object that we just created
        X400Msg x400msg = new X400Msg(bind_session);

        // Request an IPN (InterPersonal Notification)
        // These are often known as Read Receipts, and are sent by the receiving user agent
        // when the message is read from the mailbox.
        //
        // In the case below, a notification is requested in both cases, when messages are
        // read and when messages are not read. 
        // If you don't need the positive notification, just remove it. 
        int ipn_request = X400Msg.IPN_NON_RECEIPT_NOTIFICATION;

        try {
            // Send the message to itself.
            //
            // Request a delivery report (DR), that is, a message generated by the X.400 MTA that contains 
            // information about the delivery of the message. 
            // In this case below, X400Msg.Delivery_Report.DR_DELIVERY_REPORT means that reports will be generated both 
            // when the message is delivered and when it's not delivered.
            // If you don't want positive DRs, use DR_NON_DELIVERY_REPORT or DR_NO_REPORT
            //x400msg.setTo(recipient_or_address, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, ipn_request);

            // Set the subject of the message
            x400msg.setSubject(subject);

            // X.400 messages need a message identifier, that will allow us to correlate 
            // DRs (delivery reports) and IPNs (Inter-Personal Notifications) 
            // This value can be assigned here, or it can be left empty, and a random value
            // will be assigned by the API. This value can be read later with getMessageIPMIdentifier()
            //String msg_id = Long.toString((new Date()).getTime()) + "*";
            //x400msg.setMessageIPMIdentifier(msg_id);
            // Set the MTS Priority
            x400msg.setPriority(X400_Priority.NORMAL_PRIORITY);

            // Set the content, in this case a simple IA5 text bodypart
            //x400msg.setTextBody("This is the body of the test message");
            // Set an optional X.411 Security Label for the message. 
            // There are four ways to add a security label: as a file with a BER encoded byte array,
            // a file with an XML encoded string, an XML encoded String, or a JRSecurityLabel object
            //x400msg.addSecurityLabelAsBER("/opt/isode/share/x400sdk/example/c/x411seclabel.ber");
            //x400msg.addSecurityLabelAsXMLFileName("/opt/isode/share/security-label/example-data/genser-test/lConfidential.xml");
            // Add another File Transfer bodypart
            SimpleDateFormat formatter2 = new SimpleDateFormat("ddHHmm", new Locale("en"));
            Date now = new Date();
            System.out.println("Generalized Time Basic= " + formatter2.format(now));
            //atsMessage.setStringparam(X400_att.X400_S_AUTHORIZATION_TIME, formatter2.format(now));
            x400msg.setStringparam(AMHS_att.ATS_S_FILING_TIME, formatter2.format(now));
            x400msg.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, "FF");
            x400msg.setIntParam(AMHS_att.ATS_N_EXTENDED, 0);
            x400msg.setIntParam(X400_att.X400_N_CONTENT_TYPE, 22);
            x400msg.setStringparam(AMHS_att.ATS_S_TEXT, content);

//            x400msg.setStringparam(AMHS_att.ATS_S_TEXT, content);
            // Add a General Text bodypart
            //BodypartGeneralText gt1 = new BodypartGeneralText(true, "");
            //gt1.setContentFromFile("/etc/hosts");
            //x400msg.addBodypart(gt1);
            // Add a File Transfer bodypart
            //BodypartFTBP ftbp = new BodypartFTBP("/bin/ls");
            //ftbp.setApplicationReferenceOID("2.16.840.1.113694.2.2.1.1");
            //x400msg.addBodypart(ftbp);
            // Set the content type 
            // If a Message IPM Identifier wasn't assigned, read the value that was calculated
            String ipm_id = x400msg.getMessageIPMIdentifier();

            x400msg.setFrom(from);

            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC & ~  X400_att.X400_RECIP_BCC, bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_PRIMARY, to, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_CC, cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC , bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC , bccc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //
            // x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setIPMHeadingPrimaryRecipient(primary1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setIPMHeadingPrimaryRecipient(primary2, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setIPMHeadingCopyRecipient(cc1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setIPMHeadingCopyRecipient(cc2, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

            x400msg.setBcc(bcc_address, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

            //x400msg.setIPMHeadingBlindCopyRecipient(bcc,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            // Send the message to the Message Store
            //x400msg.sendMsg(bind_session);
            //x400msg.setTo(primary1,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //x400msg.setTo(primary2,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //x400msg.setCc(cc1,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setCc(cc2,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.sendMsg(bind_session);

            // Unbind cleanly from the Message Store
            // The message was correctly submitted to the Message Store
            // Retrieve the message submission ID (assigned by the MTA) and the submission time
            final String msg_sub_id = x400msg.getMessageIdentifier();
            final String msg_st = x400msg.getSubmissionTime();

            System.out.println("Message submitted.\nMessage Submission ID: "
                    + msg_sub_id + "\nIPM ID: " + ipm_id + "\nSubmission time: " + msg_st);

        } catch (X400APIException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
            System.out.println("Exception code = " + e1.getNativeErrorCode());
        }
    }

    public static void SendNormalMessage() {
        // Since the bind was successful, create a new message object using the 
        // session object that we just created
        X400Msg x400msg = new X400Msg(bind_session);

        // Request an IPN (InterPersonal Notification)
        // These are often known as Read Receipts, and are sent by the receiving user agent
        // when the message is read from the mailbox.
        //
        // In the case below, a notification is requested in both cases, when messages are
        // read and when messages are not read. 
        // If you don't need the positive notification, just remove it. 
        int ipn_request = X400Msg.IPN_NON_RECEIPT_NOTIFICATION;

        try {
            // Send the message to itself.
            //
            // Request a delivery report (DR), that is, a message generated by the X.400 MTA that contains 
            // information about the delivery of the message. 
            // In this case below, X400Msg.Delivery_Report.DR_DELIVERY_REPORT means that reports will be generated both 
            // when the message is delivered and when it's not delivered.
            // If you don't want positive DRs, use DR_NON_DELIVERY_REPORT or DR_NO_REPORT
            //x400msg.setTo(recipient_or_address, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, ipn_request);

            // Set the subject of the message
            x400msg.setSubject(subject);

            // X.400 messages need a message identifier, that will allow us to correlate 
            // DRs (delivery reports) and IPNs (Inter-Personal Notifications) 
            // This value can be assigned here, or it can be left empty, and a random value
            // will be assigned by the API. This value can be read later with getMessageIPMIdentifier()
            //String msg_id = Long.toString((new Date()).getTime()) + "*";
            //x400msg.setMessageIPMIdentifier(msg_id);
            // Set the MTS Priority
            x400msg.setPriority(X400_Priority.NORMAL_PRIORITY);

            // Set the content, in this case a simple IA5 text bodypart
            //x400msg.setTextBody("This is the body of the test message");
            // Set an optional X.411 Security Label for the message. 
            // There are four ways to add a security label: as a file with a BER encoded byte array,
            // a file with an XML encoded string, an XML encoded String, or a JRSecurityLabel object
            //x400msg.addSecurityLabelAsBER("/opt/isode/share/x400sdk/example/c/x411seclabel.ber");
            //x400msg.addSecurityLabelAsXMLFileName("/opt/isode/share/security-label/example-data/genser-test/lConfidential.xml");
            // Add another File Transfer bodypart
            //These attributes map to different X400 Attributes depending on the environment. Note that if you are using the basic message service (i.e. ATS_N_EXTENDED is not set, or is set to FALSE) you must supply all of the mandatory ATS attributes - 
            //ATS-S_PRIORITY_INDICATOR, 
            //ATS_S_FILING_TIME and 
            // ATS_S_TEXT as a set. 
            
// Basic
            /*
            
            SimpleDateFormat formatter2 = new SimpleDateFormat("ddHHmm", new Locale("en"));
            Date now = new Date();
            
            System.out.println("Generalized Time Basic= " + formatter2.format(now));
            //atsMessage.setStringparam(X400_att.X400_S_AUTHORIZATION_TIME, formatter2.format(now));
            x400msg.setStringparam(AMHS_att.ATS_S_FILING_TIME, formatter2.format(now));
            x400msg.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, "GG");
            x400msg.setIntParam(AMHS_att.ATS_N_EXTENDED, 0);
            x400msg.setStringparam(AMHS_att.ATS_S_OPTIONAL_HEADING_INFO,"ATTECH 123456789");
            x400msg.setIntParam(X400_att.X400_N_CONTENT_TYPE, 22);
            x400msg.setStringparam(AMHS_att.ATS_S_TEXT, content);
            */
            
                
// Extend
            
                      
                        x400msg.setIntParam(AMHS_att.ATS_N_EXTENDED, 1);
                       // x400msg.setStringparam(X400_att.X400_S_PRECEDENCE_POLICY_ID,"1.3.27.8.0.0");
                        x400msg.setStringparam(AMHS_att.ATS_S_FILING_TIME, "231710022712Z");
                        x400msg.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, "GG");
                        x400msg.setStringparam(X400_att.X400_S_ORIGINATORS_REFERENCE,"ATTECH 123456789");
			// Set the subject of the message
			x400msg.setSubject("TESTING SEND BY P3 VVVVZPZX");
                        x400msg.setStringparam(AMHS_att.ATS_S_TEXT, content);
                         
                        x400msg.setIntParam(X400_att.X400_N_IMPLICIT_CONVERSION_PROHIBITED, 1);
                        x400msg.setIntParam(X400_att.X400_N_CONVERSION_WITH_LOSS_PROHIBITED, 1);
                        
// ftbp            
                        
  /*                      
            //Add a General Text bodypart
            BodypartGeneralText gt1 = new BodypartGeneralText(true, "");
            gt1.setContentFromFile("F:\\Log.txt");
            x400msg.addBodypart(gt1);
   */
  
            // Add a File Transfer bodypart
           // BodypartFTBP ftbp = new BodypartFTBP("F:\\duc.jpg");
           // ftbp.setApplicationReferenceOID("2.16.840.1.113694.2.2.1.1");
           // x400msg.addBodypart(ftbp);
            // Set the content type 
                                  
                        
                        
          //  x400msg.setIntParam(X400_att.X400_S_SUPPLEMENTARY_INFO);
//            x400msg.setStringparam(X400_att.X400_S_SUPPLEMENTARY_INFO, "");

            //           x400msg.setStringparam(AMHS_att.ATS_S_TEXT, content);
            // Add a General Text bodypart
          //  BodypartGeneralText gt1 = new BodypartGeneralText(true, "");
          //  gt1.setContentFromFile("F:\\duc.jpg");
          //  x400msg.addBodypart(gt1);
            
            // Add a File Transfer bodypart
            //BodypartFTBP ftbp = new BodypartFTBP("/bin/ls");
            //ftbp.setApplicationReferenceOID("2.16.840.1.113694.2.2.1.1");
            //x400msg.addBodypart(ftbp);
            // Set the content type 
            // If a Message IPM Identifier wasn't assigned, read the value that was calculate   

// ftbp
            
            String ipm_id = x400msg.getMessageIPMIdentifier();

            x400msg.setFrom(from);

            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC & ~  X400_att.X400_RECIP_BCC, bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_PRIMARY, to, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_CC, cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC , bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC , bccc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //
            // x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingPrimaryRecipient(to, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingPrimaryRecipient(to1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingCopyRecipient(cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingCopyRecipient(cc1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingBlindCopyRecipient(bcc,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            // Send the message to the Message Store
            //x400msg.sendMsg(bind_session);
            //String to = "/OU=VVTSMHSX/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
            //String to = "/OU=VVTSMHSX/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
            //String to = "/OU=CHAUDUC/O=CONDUC/PRMD=DUC/ADMD=ICAO/C=XX/";
            //String to = "/OU=WAAAMHSX/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
            //String to    = "/CN=WSSSMHSA/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
            
            
            //String to  = "/OU=VVTSMHSA/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
            // String to = "/CN=WSSSFTNA/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
            //String to1 = "/OU=VVTSPPPP/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
            //String to2 = "/OU=VVTSMHSC/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
            //String to3 = "/OU=VVTSMMBA/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
            
            ////String to3 = "/OU=VVTSMHBA/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
            
            
            //String to  = "/OU=VVTSFTNX/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
            //String to = "/CN=WSSSFTNA/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
            //String to1 = "/CN=WSSSMHSA/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
            
            //String to2  = "/CN=VVTSOPTA/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
            //String to3  = "/OU=VVTSFTNA/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";
            
            
            
            String to2  = "/CN=VVTSOPTC/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
            
             
            //x400msg.setTo(to, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_RECEIPT_NOTIFICATION);
            //x400msg.setTo(to1, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_RECEIPT_NOTIFICATION);
            x400msg.setTo(to2, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_RECEIPT_NOTIFICATION);
            //x400msg.setTo(to3, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_RECEIPT_NOTIFICATION);
            
            x400msg.sendMsg(bind_session);

            // Unbind cleanly from the Message Store
            // The message was correctly submitted to the Message Store
            // Retrieve the message submission ID (assigned by the MTA) and the submission time
            final String msg_sub_id = x400msg.getMessageIdentifier();
            final String msg_st = x400msg.getSubmissionTime();

            System.out.println("Message submitted.\nMessage Submission ID: "
                    + msg_sub_id + "\nIPM ID: " + ipm_id + "\nSubmission time: " + msg_st);

        } catch (X400APIException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
            System.out.println("Exception code = " + e1.getNativeErrorCode());
//            try {
//                bind_session.unbind();
//            } catch (X400APIException e) {
//            }
//            System.exit(1);
        }
    }

    public static void SendTest() {

        // Since the bind was successful, create a new message object using the 
        // session object that we just created
        X400Msg x400msg = new X400Msg(bind_session);

        // Request an IPN (InterPersonal Notification)
        // These are often known as Read Receipts, and are sent by the receiving user agent
        // when the message is read from the mailbox.
        //
        // In the case below, a notification is requested in both cases, when messages are
        // read and when messages are not read. 
        // If you don't need the positive notification, just remove it. 
        //int ipn_request = X400Msg.IPN_NON_RECEIPT_NOTIFICATION;
        try {
            // Send the message to itself.
            //
            // Request a delivery report (DR), that is, a message generated by the X.400 MTA that contains 
            // information about the delivery of the message. 
            // In this case below, X400Msg.Delivery_Report.DR_DELIVERY_REPORT means that reports will be generated both 
            // when the message is delivered and when it's not delivered.
            // If you don't want positive DRs, use DR_NON_DELIVERY_REPORT or DR_NO_REPORT
            //x400msg.setTo(recipient_or_address, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, ipn_request);

            // Set the subject of the message
            x400msg.setSubject(subject);

            // X.400 messages need a message identifier, that will allow us to correlate 
            // DRs (delivery reports) and IPNs (Inter-Personal Notifications) 
            // This value can be assigned here, or it can be left empty, and a random value
            // will be assigned by the API. This value can be read later with getMessageIPMIdentifier()
            //String msg_id = Long.toString((new Date()).getTime()) + "*";
            //x400msg.setMessageIPMIdentifier(msg_id);
            // Set the MTS Priority
            x400msg.setPriority(X400_Priority.NORMAL_PRIORITY);

            // Set the content, in this case a simple IA5 text bodypart
            //x400msg.setTextBody("This is the body of the test message");
            // Set an optional X.411 Security Label for the message. 
            // There are four ways to add a security label: as a file with a BER encoded byte array,
            // a file with an XML encoded string, an XML encoded String, or a JRSecurityLabel object
            //x400msg.addSecurityLabelAsBER("/opt/isode/share/x400sdk/example/c/x411seclabel.ber");
            //x400msg.addSecurityLabelAsXMLFileName("/opt/isode/share/security-label/example-data/genser-test/lConfidential.xml");
            // Add another File Transfer bodypart
            BodypartIA5Text ia5 = new BodypartIA5Text(content);
            x400msg.addBodypart(ia5);

            // Add a General Text bodypart
            //BodypartGeneralText gt1 = new BodypartGeneralText(true, "");
            //gt1.setContentFromFile("/etc/hosts");
            //x400msg.addBodypart(gt1);
            // Add a File Transfer bodypart
            //BodypartFTBP ftbp = new BodypartFTBP("/bin/ls");
            //ftbp.setApplicationReferenceOID("2.16.840.1.113694.2.2.1.1");
            //x400msg.addBodypart(ftbp);
            // Set the content type 
            x400msg.setIntParam(X400_att.X400_N_CONTENT_TYPE, 22);

            // If a Message IPM Identifier wasn't assigned, read the value that was calculated
            String ipm_id = x400msg.getMessageIPMIdentifier();

            x400msg.setFrom(from);

            String pr1 = "/OU=VVTSAMHS/O=AFTN/PRMD=VV/ADMD=ICAO/C=XX/";

            x400msg.setRecipient(true, X400_att.X400_RECIP_PRIMARY, pr1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_PRIMARY, primary1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

            // x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingPrimaryRecipient(to, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingPrimaryRecipient(to1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingCopyRecipient(cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingCopyRecipient(cc1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingBlindCopyRecipient(bcc,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            // Send the message to the Message Store
            //x400msg.sendMsg(bind_session);
            //x400msg.setTo(primary1,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //x400msg.setTo(primary2,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //x400msg.setCc(cc1,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setCc(cc2,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.sendMsg(bind_session);

            // Unbind cleanly from the Message Store
            // The message was correctly submitted to the Message Store
            // Retrieve the message submission ID (assigned by the MTA) and the submission time
            final String msg_sub_id = x400msg.getMessageIdentifier();
            final String msg_st = x400msg.getSubmissionTime();

            System.out.println("Message submitted.\nMessage Submission ID: "
                    + msg_sub_id + "\nIPM ID: " + ipm_id + "\nSubmission time: " + msg_st);

        } catch (X400APIException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
            System.out.println("Exception code = " + e1.getNativeErrorCode());
        }

    }

    static String pr1 = "/CN=WSSSMHSA/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
    static String pr2 = "/CN=WSSSFTNA/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
    static String pr3 = "/CN=WSSSFTNB/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";

    static String pr4 = "/CN=WSSSFTNA/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
    static String pr5 = "/CN=WSSSFTUU/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
    static String pr6 = "/CN=WSSSFTUY/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
    static String pr7 = "/CN=WSSSFTYX/OU=WSSY/O=CAASY/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";

    static public void MyProbe() {

        X400Msg x400msg = new X400Msg(bind_session, true);

        try {

            //x400msg.setSubject(subject);
            //x400msg.setPriority(X400_Priority.NORMAL_PRIORITY);
            //SimpleDateFormat formatter2 = new SimpleDateFormat("ddHHmm", new Locale("en"));
            //Date now = new Date();
            //System.out.println("Generalized Time Basic= " + formatter2.format(now));
            ////atsMessage.setStringparam(X400_att.X400_S_AUTHORIZATION_TIME, formatter2.format(now));
            //x400msg.setStringparam(AMHS_att.ATS_S_FILING_TIME, formatter2.format(now));
            //x400msg.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, "FF");
            //x400msg.setIntParam(AMHS_att.ATS_N_EXTENDED, 0);
            //x400msg.setIntParam(X400_att.X400_N_CONTENT_TYPE, 22);
            //x400msg.setStringparam(AMHS_att.ATS_S_TEXT, content);
            //String ipm_id = x400msg.getMessageIPMIdentifier();
            //x400msg.setFrom(from);
            x400msg.setTo(pr1, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setTo(pr2, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setTo(pr3, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

            //String contentLenght = "10";
//            x400msg.setIntParam(X400_att.X400_N_DL_EXPANSION_PROHIBITED, 1);
//            x400msg.setIntParam(X400_att.X400_N_ALTERNATE_RECIPIENT_ALLOWED, 0);          // NO NEED
//            x400msg.setIntParam(X400_att.X400_N_RECIPIENT_REASSIGNMENT_PROHIBITED, 0);    // NO NEED
//            x400msg.setIntParam(X400_att.X400_N_IMPLICIT_CONVERSION_PROHIBITED, 0);       // NO NEED
//            x400msg.setIntParam(X400_att.X400_N_CONVERSION_WITH_LOSS_PROHIBITED, 0);      // NO NEED
            x400msg.setStringparam(X400_att.X400_S_ORIGINAL_ENCODED_INFORMATION_TYPES, "ia5-text");

            x400msg.setIntParam(X400_att.X400_N_CONTENT_TYPE, 22);
            //x400msg.setIntParam(X400_att.X400_N_CONTENT_LENGTH, Integer.parseInt(contentLenght));

            String ipm_id = x400msg.getMessageIPMIdentifier();

            // Send the message to the Message Store
            x400msg.sendMsg(bind_session);

            final String msg_sub_id = x400msg.getMessageIdentifier();
            final String msg_st = x400msg.getSubmissionTime();

            System.out.println("Message submitted.\nMessage Submission ID: "
                    + msg_sub_id + "\nIPM ID: " + ipm_id + "\nSubmission time: " + msg_st);

        } catch (X400APIException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
            System.out.println("Exception code = " + e1.getNativeErrorCode());
        }
    }

    static public void PureProbe() {
        X400Msg x400msg = new X400Msg(bind_session, true);
        try {

            //x400msg.setTo(pr1, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setTo(pr2, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setTo(pr3, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setRecipient(X400_att.X400_RECIP_PRIMARY, pr4, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setRecipient(X400_att.X400_RECIP_PRIMARY, pr7, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

            x400msg.setStringparam(X400_att.X400_S_ORIGINAL_ENCODED_INFORMATION_TYPES, "ia5-text");

            String ipm_id = x400msg.getMessageIPMIdentifier();

            x400msg.sendMsg(bind_session);

            final String msg_sub_id = x400msg.getMessageIdentifier();
            final String msg_st = x400msg.getSubmissionTime();

            System.out.println("Message submitted.\nMessage Submission ID: "
                    + msg_sub_id + "\nIPM ID: " + ipm_id + "\nSubmission time: " + msg_st);

        } catch (X400APIException e1) {
            e1.printStackTrace();
            System.out.println("Exception code = " + e1.getNativeErrorCode());
        }
    }

    static public void sent_Probe() {
        try {
            try {

                X400Msg x400msg = new X400Msg(bind_session, true);

                //for (OutboxAddress addrss : mdlRecipient.getOutboxAddress()) {
                //    if (addrss.getType().equals("P")) {
                //        this.addRecip(x400msg, addrss.getReportRequest(), addrss.getIpnRequest(), addrss.getAddress());
                //    }
                // }
                x400msg.setRecipient(X400_att.X400_RECIP_PRIMARY, pr4, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
                //x400msg.setRecipient(X400_att.X400_RECIP_PRIMARY, pr2, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
                //x400msg.setRecipient(X400_att.X400_RECIP_PRIMARY, pr3, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

                x400msg.setRecipient(X400_att.X400_RECIP_PRIMARY, pr5, X400Msg.DR_Request.DR_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

                //String contentLenght = jtxt_leght_Probe.getText();
                String contentLenght = "TEST 123";
//                x400msg.setIntParam(X400_att.X400_N_DL_EXPANSION_PROHIBITED, 1);
//
//                x400msg.setIntParam(X400_att.X400_N_ALTERNATE_RECIPIENT_ALLOWED, 0);
//                x400msg.setIntParam(X400_att.X400_N_RECIPIENT_REASSIGNMENT_PROHIBITED, 0);
//                x400msg.setIntParam(X400_att.X400_N_IMPLICIT_CONVERSION_PROHIBITED, 0);
//                x400msg.setIntParam(X400_att.X400_N_CONVERSION_WITH_LOSS_PROHIBITED, 0);
                x400msg.setStringparam(X400_att.X400_S_ORIGINAL_ENCODED_INFORMATION_TYPES, "ia5-text");

//                x400msg.setStringparam(AMHS_att.ATS_S_FILING_TIME, formatter2.format(now));
//                x400msg.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, "FF");
//                x400msg.setIntParam(AMHS_att.ATS_N_EXTENDED, 0);
//                x400msg.setStringparam(AMHS_att.ATS_S_TEXT, content);
                x400msg.setIntParam(X400_att.X400_N_CONTENT_TYPE, 22);
                x400msg.setIntParam(X400_att.X400_N_CONTENT_LENGTH, Integer.parseInt(contentLenght));

                String ipm_id = x400msg.getMessageIPMIdentifier();

                // Send the message to the Message Store
                x400msg.sendMsg(bind_session);
                final String msg_sub_id = x400msg.getMessageIdentifier();
                final String msg_st = x400msg.getSubmissionTime();

                System.out.println("Message submitted.\nMessage Submission ID: " + msg_sub_id + "\nIPM ID: " + ipm_id + "\nSubmission time: " + msg_st);

            } catch (X400APIException e1) {
                System.out.println("Exception code = " + e1.getNativeErrorCode());

            }
        } catch (NumberFormatException e1) {

            System.exit(1);
        }
    }

    public static void main(String[] args) {

        System.out.println("Connecting to the P7 Message Store... ");

        // Create a new P7 bind session object with the session values necessary for the bind
        connection = new P7BindSession(p7_message_store_presentation_address,
                p7_user_or_address, p7_user_password);

        // Bind to the P7 Message Store
        try {
            connection.bind();
        } catch (X400APIException e) {
            System.exit(1);
        }

        bind_session = connection;

        //SendBCC(bcc2);
        //SendBCC(bcc1);
        //SendTOCC();
        //sent_Probe();
        //MyProbe();
        //PureProbe();
        // Kiem tra BCC tren 1 dien van
        //for(int i = 0 ; i < 10 ; i++) {
        //    content = "AUTO TEST STRESS DIEN VAN " + Integer.toString(i+1);
            content = "AUTO TEST EXTENED DIEN VAN ";
            SendNormalMessage();
        //    try {
        //        Thread.sleep(1000);
         //   } catch (InterruptedException ex) {
          //      Logger.getLogger(SendX400Mail.class.getName()).log(Level.SEVERE, null, ex);
          //  }
        //}
        
        //

        // Kiem tra dien BT
        //SendTest();
        //
        try {
            bind_session.unbind();
        } catch (X400APIException ex) {
            Logger.getLogger(SendX400Mail_extend.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
