/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/* 
 * Copyright (c) 2008-2010, Isode Limited, London, England.
 * All rights reserved.
 * 
 * Acquisition and use of this software and related materials for any
 * purpose requires a written licence agreement from Isode Limited,
 * or a written licence from an organisation licenced by Isode Limited
 * to grant such a licence.
 */
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import com.isode.x400.highlevel.P3BindSession;
import com.isode.x400.highlevel.P7BindSession;
import com.isode.x400.highlevel.ReceiveMsg;
import com.isode.x400.highlevel.X400APIException;
import com.isode.x400.highlevel.X400Msg;
import com.isode.x400api.AMHS_att;
import com.isode.x400api.MSMessage;
import com.isode.x400api.X400_att;
import com.isode.x400api.X400ms;

/**
 * Test program that connects to a P7 Message Store, and submits an aviation
 * (ATS) message
 *
 */
public class SendIPN2 {

    //private static String p7_message_store_presentation_address = "\"3001\"/Internet=spec.isode.net+3001";
    //private static String p7_message_store_presentation_address = "'6101'H//\"TCP\"/Internet=192.168.22.199+6101";
    private static String p7_message_store_presentation_address = "\"3001\"/Internet=192.168.22.199+3001";

    private static String p7_user_or_address = "/CN=VVNBZQZX/OU=VVNB/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    private static String p7_user_password = "amhs";
    private static String recipient_or_address = "/CN=VVTSSWIM/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    private static boolean extended = false;

    public static void main(String[] args) {

        P3BindSession bind_session;

        System.out.println("Connecting to the P7 Message Store...");
        
        System.out.println(p7_message_store_presentation_address);

        // Create a new P7 bind session object with the session values necessary for the bind
        P7BindSession connection = new P7BindSession(p7_message_store_presentation_address,
                p7_user_or_address, p7_user_password);

        // Bind to the P7 Message Store
        try {
            connection.bind();
        } catch (X400APIException e) {
            e.printStackTrace();
            System.exit(1);
        }

     //   bind_session = connection;
        
        /*

        // Since the bind was successful, create a new message object using the 
        // session object that we just created
        X400Msg atsMessage = new X400Msg(bind_session);

        // Request an IPN (InterPersonal Notification)
        // These are often known as Read Receipts, and are sent by the receiving user agent
        // when the message is read from the mailbox.
        //
        // In the case below, a notification is requested in both cases, when messages are
        // read and when messages are not read. 
        // If you don't need the positive notification, just remove it. 
        int ipn_request = X400Msg.IPN_NON_RECEIPT_NOTIFICATION;

        try {
            // Send the message to itself.
            //
            // Request a delivery report (DR), that is, a message generated by the X.400 MTA that contains 
            // information about the delivery of the message. 
            // In this case below, X400Msg.Delivery_Report.DR_DELIVERY_REPORT means that reports will be generated both 
            // when the message is delivered and when it's not delivered.
            // If you don't want positive DRs, use DR_NON_DELIVERY_REPORT or DR_NO_REPORT
            atsMessage.setTo(recipient_or_address, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, ipn_request);

            // Set the subject of the message
            //atsMessage.setSubject("Testing HLJXA for Aviation");
            //   atsMessage.setSubject("ATETCH TESTING HLJXA FOR AVIATION");
            // X.400 messages need a message identifier, that will allow us to correlate 
            // DRs (delivery reports) and IPNs (Inter-Personal Notifications) 
            // This value can be assigned here, or it can be left empty, and a random value
            // will be assigned by the API. This value can be read later with getMessageIPMIdentifier()
            //String msg_id = Long.toString((new Date()).getTime()) + "*";
            //x400msg.setMessageIPMIdentifier(msg_id);
            if (extended) {
                atsMessage.setIntParam(AMHS_att.ATS_N_EXTENDED, 1);

                // The Filing Time, in Extended Encoding
                // The format expected by the X.400 API is UTC Time (yyMMddHHmmssZ) 
                SimpleDateFormat formatter2 = new SimpleDateFormat("yyMMddHHmmssZ", new Locale("en"));
                Date now = new Date();
                //atsMessage.setStringparam(X400_att.X400_S_AUTHORIZATION_TIME, formatter2.format(now));
                atsMessage.setStringparam(AMHS_att.ATS_S_FILING_TIME, formatter2.format(now));

                // No need to set the Precedence Policy ID to "1.3.27.8.0.0", as it is set by the ATS_N_EXTENDED
                //atsMessage.setStringparam(X400_att.X400_S_PRECEDENCE_POLICY_ID,"1.3.27.8.0.0");
                // The Priority, as an Integer. 
                // 57 == FF
                //atsMessage.setAllRecipPrecedence(57);
                atsMessage.setTo(recipient_or_address, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, ipn_request);
                atsMessage.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, "DD");
                atsMessage.setStringparam(AMHS_att.ATS_S_TEXT, "TEST XXX");
                // Set the Originator's Reference
                //atsMessage.setStringparam(X400_att.X400_S_ORIGINATORS_REFERENCE, "MY EXTENDED REFERENCE");

            } else {

                atsMessage.setIntParam(AMHS_att.ATS_N_EXTENDED, 0);

                // The Filing Time, in Basic Encoding
                SimpleDateFormat formatter2 = new SimpleDateFormat("ddHHmm", new Locale("en"));
                Date now = new Date();
                atsMessage.setStringparam(AMHS_att.ATS_S_FILING_TIME, formatter2.format(now));

                // The Priority, as two letters
                atsMessage.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, "FF");

                // Set the Originator's Reference
                atsMessage.setStringparam(X400_att.X400_S_ORIGINATORS_REFERENCE, "MY BASIC REFERENCE");
            }

            // Set the content type 
            atsMessage.setIntParam(X400_att.X400_N_CONTENT_TYPE, 22);

            // Set the content of the ATS message (which will become an IA5 Text bodypart)
            //atsMessage.setStringparam(AMHS_att.ATS_S_TEXT, "THIS IS THE CONTENT OF ATS MESSAGE");
            //  atsMessage.setStringparam(X400_att.X400_S_GENERAL_TEXT_CHARSETS,"1 6");
            //   atsMessage.setStringparam(X400_att.X400_T_GENERAL_TEXT, "THIS IS THE CONTENT OF ATS MESSAGE");
            //setStrParam(msMessage, X400_att.X400_T_GENERAL_TEXT, outbox.getContent());
            // If a Message IPM Identifier wasn't assigned, read the value that was calculated
            String ipm_id = atsMessage.getMessageIPMIdentifier();

            
            atsMessage.setMessageIPMIdentifier(ipm_id);
            
            */
            
    
        try {        
            // ReceiveMsg rm = new ReceiveMsg(connection);
            ReceiveMsg rms = new ReceiveMsg(connection, 345281);

            MSMessage ipnMessage = new MSMessage();

            int result = X400ms.x400_ms_msgmakeIPN(rms, 0, ipnMessage);
            rms.getMessageIdentifier();

            //  X400Msg atsMessage1  =  (X400Msg)ipnMessage;
            // Send the message to the Message Store
            //atsMessage.sendMsg(bind_session);
            int code = X400ms.x400_ms_msgsend(ipnMessage);

            if (code != X400_att.X400_E_NOERROR) {
                System.out.println("ERROR");
                //     String errorDetail = X400ms.x400_ms_get_string_error(bind_session, code);
                //    String errorMessage = "Sending message fail: " + errorDetail;
                //    throw new X400APIException(errorMessage, code);
            } else {
                System.out.println("Ok");
            }

            // Unbind cleanly from the Message Store
            connection.unbind();

            // The message was correctly submitted to the Message Store
            // Retrieve the message submission ID (assigned by the MTA) and the submission time
            //   final String msg_sub_id = atsMessage.getMessageIdentifier();
            //   final String msg_st = atsMessage.getSubmissionTime();
            //   System.out.println("Message submitted.\nMessage Submission ID: "
            //           + msg_sub_id + "\nIPM ID: " + ipm_id + "\nSubmission time: " + msg_st);
        } catch (X400APIException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
            System.out.println("Exception code = " + e1.getNativeErrorCode());
            try {
                connection.unbind();
            } catch (X400APIException e) {
            }
            System.exit(1);
        }

    }

}
