    package javaapplication1;


import com.isode.x400.highlevel.BodypartIA5Text;
import com.isode.x400.highlevel.P3BindSession;
import com.isode.x400.highlevel.P7BindSession;
import com.isode.x400.highlevel.X400Msg;
import com.isode.x400.highlevel.X400APIException;
import com.isode.x400.highlevel.X400Msg.X400_Priority;
import com.isode.x400api.AMHS_att;
import com.isode.x400api.X400_att;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Test program that connects to either an MTA's P3 channel or to a P7 Message
 * Store, and submits a test message to itself.
 *
 */
public class SendX400Mail_1 {

    private static String p7_message_store_presentation_address = "\"3001\"/URI+0000+URL+itot://192.168.22.186:3001";
    private static String p7_user_or_address = "/CN=VVTSOPTA/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    private static String p7_user_password = "amhs";

    private static String recipient_or_address = "/CN=VVTSOPTA/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

//    private static String primary1 = "/OU=VVTSMHSA/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
//    private static String primary2 = "/OU=VVTSOPTA/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
//
//    private static String cc1 = "/OU=VVTSMHSB/O=AFTN/PRMD=VVIETNAMV/ADMD=ICAO/C=XX/";
//    private static String cc2 = "/OU=VVTSOPTB/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
//
//    private static String bcc1 = "/OU=VVTSMHSC/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
//    private static String bcc2 = "/OU=VVTSOPTC/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    private static String primary1 = "/CN=VVTSOPTB/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    private static String primary2 = "/CN=WSSSFTNA/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";

    private static String cc1 = "/CN=WSSSMHSB/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
    private static String cc2 = "/CN=WSSSFTNB/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";

    private static String bcc1 = "/CN=WSSSMHSC/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";
    private static String bcc2 = "/CN=WSSSFTNC/OU=WSSS/O=CAASG/PRMD=SINGAPORE/ADMD=ICAO/C=XX/";

    /*
    private static String primary1 = "/OU=VVTSOPTA/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    private static String primary2 = "/OU=VVTSOPTB/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static String cc1 = "/OU=VVTSOPTC/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    private static String cc2 = "/OU=VVTSOPTD/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static String bcc1 = "/OU=VVTSOPTE/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    private static String bcc2 = "/OU=VVTSOPTF/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";
    
     */
    private static String subject = "TEST IT501/TC05";
    private static String content = "TEST IT501/TC05";

    private static String from = "/CN=VVTSOPTA/OU=VVTS/O=VVTS/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

    private static P3BindSession bind_session;

    private static P7BindSession connection;

    public static void SendTOCC() {

        // Since the bind was successful, create a new message object using the 
        // session object that we just created
        X400Msg x400msg = new X400Msg(bind_session);

        // Request an IPN (InterPersonal Notification)
        // These are often known as Read Receipts, and are sent by the receiving user agent
        // when the message is read from the mailbox.
        //
        // In the case below, a notification is requested in both cases, when messages are
        // read and when messages are not read. 
        // If you don't need the positive notification, just remove it. 
        int ipn_request = X400Msg.IPN_NON_RECEIPT_NOTIFICATION;

        try {
            // Send the message to itself.
            //
            // Request a delivery report (DR), that is, a message generated by the X.400 MTA that contains 
            // information about the delivery of the message. 
            // In this case below, X400Msg.Delivery_Report.DR_DELIVERY_REPORT means that reports will be generated both 
            // when the message is delivered and when it's not delivered.
            // If you don't want positive DRs, use DR_NON_DELIVERY_REPORT or DR_NO_REPORT
            //x400msg.setTo(recipient_or_address, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, ipn_request);

            // Set the subject of the message
            x400msg.setSubject(subject);

            // X.400 messages need a message identifier, that will allow us to correlate 
            // DRs (delivery reports) and IPNs (Inter-Personal Notifications) 
            // This value can be assigned here, or it can be left empty, and a random value
            // will be assigned by the API. This value can be read later with getMessageIPMIdentifier()
            //String msg_id = Long.toString((new Date()).getTime()) + "*";
            //x400msg.setMessageIPMIdentifier(msg_id);
            // Set the MTS Priority
            x400msg.setPriority(X400_Priority.NORMAL_PRIORITY);

            // Set the content, in this case a simple IA5 text bodypart
            //x400msg.setTextBody("This is the body of the test message");
            // Set an optional X.411 Security Label for the message. 
            // There are four ways to add a security label: as a file with a BER encoded byte array,
            // a file with an XML encoded string, an XML encoded String, or a JRSecurityLabel object
            //x400msg.addSecurityLabelAsBER("/opt/isode/share/x400sdk/example/c/x411seclabel.ber");
            //x400msg.addSecurityLabelAsXMLFileName("/opt/isode/share/security-label/example-data/genser-test/lConfidential.xml");
            // Add another File Transfer bodypart
//            BodypartIA5Text ia5 = new BodypartIA5Text(content);
//            x400msg.addBodypart(ia5);


            SimpleDateFormat formatter2 = new SimpleDateFormat("ddHHmm", new Locale("en"));
            Date now = new Date();
            System.out.println("Generalized Time Basic= " + formatter2.format(now));
            //atsMessage.setStringparam(X400_att.X400_S_AUTHORIZATION_TIME, formatter2.format(now));
            x400msg.setStringparam(AMHS_att.ATS_S_FILING_TIME, formatter2.format(now));
            x400msg.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, "FF");
            x400msg.setIntParam(AMHS_att.ATS_N_EXTENDED, 0);
            x400msg.setStringparam(AMHS_att.ATS_S_TEXT, content);
            
            
            // Add a General Text bodypart
            //BodypartGeneralText gt1 = new BodypartGeneralText(true, "");
            //gt1.setContentFromFile("/etc/hosts");
            //x400msg.addBodypart(gt1);
            // Add a File Transfer bodypart
            //BodypartFTBP ftbp = new BodypartFTBP("/bin/ls");
            //ftbp.setApplicationReferenceOID("2.16.840.1.113694.2.2.1.1");
            //x400msg.addBodypart(ftbp);
            // Set the content type 
            x400msg.setIntParam(X400_att.X400_N_CONTENT_TYPE, 22);

            // If a Message IPM Identifier wasn't assigned, read the value that was calculated
            String ipm_id = x400msg.getMessageIPMIdentifier();

            x400msg.setFrom(from);

            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC & ~  X400_att.X400_RECIP_BCC, bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_PRIMARY, to, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_CC, cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC , bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC , bccc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //
            // x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingPrimaryRecipient(to, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingPrimaryRecipient(to1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingCopyRecipient(cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingCopyRecipient(cc1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingBlindCopyRecipient(bcc,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            // Send the message to the Message Store
            //x400msg.sendMsg(bind_session);
            x400msg.setTo(primary1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setTo(primary2, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setCc(cc1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setCc(cc2, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

            x400msg.sendMsg(bind_session);

            // Unbind cleanly from the Message Store
            // The message was correctly submitted to the Message Store
            // Retrieve the message submission ID (assigned by the MTA) and the submission time
            final String msg_sub_id = x400msg.getMessageIdentifier();
            final String msg_st = x400msg.getSubmissionTime();

            System.out.println("Message submitted.\nMessage Submission ID: "
                    + msg_sub_id + "\nIPM ID: " + ipm_id + "\nSubmission time: " + msg_st);

        } catch (X400APIException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
            System.out.println("Exception code = " + e1.getNativeErrorCode());
//            try {
//                bind_session.unbind();
//            } catch (X400APIException e) {
//            }
//            System.exit(1);
        }
    }

    public static void SendBCC(String bcc_address) {

        // Since the bind was successful, create a new message object using the 
        // session object that we just created
        X400Msg x400msg = new X400Msg(bind_session);

        // Request an IPN (InterPersonal Notification)
        // These are often known as Read Receipts, and are sent by the receiving user agent
        // when the message is read from the mailbox.
        //
        // In the case below, a notification is requested in both cases, when messages are
        // read and when messages are not read. 
        // If you don't need the positive notification, just remove it. 
        int ipn_request = X400Msg.IPN_NON_RECEIPT_NOTIFICATION;

        try {
            // Send the message to itself.
            //
            // Request a delivery report (DR), that is, a message generated by the X.400 MTA that contains 
            // information about the delivery of the message. 
            // In this case below, X400Msg.Delivery_Report.DR_DELIVERY_REPORT means that reports will be generated both 
            // when the message is delivered and when it's not delivered.
            // If you don't want positive DRs, use DR_NON_DELIVERY_REPORT or DR_NO_REPORT
            //x400msg.setTo(recipient_or_address, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, ipn_request);

            // Set the subject of the message
            x400msg.setSubject(subject);

            // X.400 messages need a message identifier, that will allow us to correlate 
            // DRs (delivery reports) and IPNs (Inter-Personal Notifications) 
            // This value can be assigned here, or it can be left empty, and a random value
            // will be assigned by the API. This value can be read later with getMessageIPMIdentifier()
            //String msg_id = Long.toString((new Date()).getTime()) + "*";
            //x400msg.setMessageIPMIdentifier(msg_id);
            // Set the MTS Priority
            x400msg.setPriority(X400_Priority.NORMAL_PRIORITY);

            // Set the content, in this case a simple IA5 text bodypart
            //x400msg.setTextBody("This is the body of the test message");
            // Set an optional X.411 Security Label for the message. 
            // There are four ways to add a security label: as a file with a BER encoded byte array,
            // a file with an XML encoded string, an XML encoded String, or a JRSecurityLabel object
            //x400msg.addSecurityLabelAsBER("/opt/isode/share/x400sdk/example/c/x411seclabel.ber");
            //x400msg.addSecurityLabelAsXMLFileName("/opt/isode/share/security-label/example-data/genser-test/lConfidential.xml");
            // Add another File Transfer bodypart
//            BodypartIA5Text ia5 = new BodypartIA5Text(content);
//            x400msg.addBodypart(ia5);
            SimpleDateFormat formatter2 = new SimpleDateFormat("ddHHmm", new Locale("en"));
            Date now = new Date();
            System.out.println("Generalized Time Basic= " + formatter2.format(now));
            //atsMessage.setStringparam(X400_att.X400_S_AUTHORIZATION_TIME, formatter2.format(now));
            x400msg.setStringparam(AMHS_att.ATS_S_FILING_TIME, formatter2.format(now));
            x400msg.setStringparam(AMHS_att.ATS_S_PRIORITY_INDICATOR, "FF");
            x400msg.setIntParam(AMHS_att.ATS_N_EXTENDED, 0);
            x400msg.setStringparam(AMHS_att.ATS_S_TEXT, content);
            // Add a General Text bodypart
            //BodypartGeneralText gt1 = new BodypartGeneralText(true, "");
            //gt1.setContentFromFile("/etc/hosts");
            //x400msg.addBodypart(gt1);
            // Add a File Transfer bodypart
            //BodypartFTBP ftbp = new BodypartFTBP("/bin/ls");
            //ftbp.setApplicationReferenceOID("2.16.840.1.113694.2.2.1.1");
            //x400msg.addBodypart(ftbp);
            // Set the content type 
            x400msg.setIntParam(X400_att.X400_N_CONTENT_TYPE, 22);

            // If a Message IPM Identifier wasn't assigned, read the value that was calculated
            String ipm_id = x400msg.getMessageIPMIdentifier();

            x400msg.setFrom(from);

            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC & ~  X400_att.X400_RECIP_BCC, bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_PRIMARY, to, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_CC, cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC , bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_BCC , bccc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //
            // x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setIPMHeadingPrimaryRecipient(primary1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setIPMHeadingPrimaryRecipient(primary2, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setIPMHeadingCopyRecipient(cc1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.setIPMHeadingCopyRecipient(cc2, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

            x400msg.setBcc(bcc_address, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

            //x400msg.setIPMHeadingBlindCopyRecipient(bcc,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            // Send the message to the Message Store
            //x400msg.sendMsg(bind_session);
            //x400msg.setTo(primary1,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //x400msg.setTo(primary2,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //x400msg.setCc(cc1,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setCc(cc2,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.sendMsg(bind_session);

            // Unbind cleanly from the Message Store
            // The message was correctly submitted to the Message Store
            // Retrieve the message submission ID (assigned by the MTA) and the submission time
            final String msg_sub_id = x400msg.getMessageIdentifier();
            final String msg_st = x400msg.getSubmissionTime();

            System.out.println("Message submitted.\nMessage Submission ID: "
                    + msg_sub_id + "\nIPM ID: " + ipm_id + "\nSubmission time: " + msg_st);

        } catch (X400APIException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
            System.out.println("Exception code = " + e1.getNativeErrorCode());
//            try {
//                bind_session.unbind();
//            } catch (X400APIException e) {
//            }
//            System.exit(1);
        }
    }

    public static void Send() {

        // Since the bind was successful, create a new message object using the 
        // session object that we just created
        X400Msg x400msg = new X400Msg(bind_session);

        // Request an IPN (InterPersonal Notification)
        // These are often known as Read Receipts, and are sent by the receiving user agent
        // when the message is read from the mailbox.
        //
        // In the case below, a notification is requested in both cases, when messages are
        // read and when messages are not read. 
        // If you don't need the positive notification, just remove it. 
        int ipn_request = X400Msg.IPN_NON_RECEIPT_NOTIFICATION;

        try {
            // Send the message to itself.
            //
            // Request a delivery report (DR), that is, a message generated by the X.400 MTA that contains 
            // information about the delivery of the message. 
            // In this case below, X400Msg.Delivery_Report.DR_DELIVERY_REPORT means that reports will be generated both 
            // when the message is delivered and when it's not delivered.
            // If you don't want positive DRs, use DR_NON_DELIVERY_REPORT or DR_NO_REPORT
            //x400msg.setTo(recipient_or_address, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, ipn_request);

            // Set the subject of the message
            x400msg.setSubject(subject);

            // X.400 messages need a message identifier, that will allow us to correlate 
            // DRs (delivery reports) and IPNs (Inter-Personal Notifications) 
            // This value can be assigned here, or it can be left empty, and a random value
            // will be assigned by the API. This value can be read later with getMessageIPMIdentifier()
            //String msg_id = Long.toString((new Date()).getTime()) + "*";
            //x400msg.setMessageIPMIdentifier(msg_id);
            // Set the MTS Priority
            x400msg.setPriority(X400_Priority.NORMAL_PRIORITY);

            // Set the content, in this case a simple IA5 text bodypart
            //x400msg.setTextBody("This is the body of the test message");
            // Set an optional X.411 Security Label for the message. 
            // There are four ways to add a security label: as a file with a BER encoded byte array,
            // a file with an XML encoded string, an XML encoded String, or a JRSecurityLabel object
            //x400msg.addSecurityLabelAsBER("/opt/isode/share/x400sdk/example/c/x411seclabel.ber");
            //x400msg.addSecurityLabelAsXMLFileName("/opt/isode/share/security-label/example-data/genser-test/lConfidential.xml");
            // Add another File Transfer bodypart
            BodypartIA5Text ia5 = new BodypartIA5Text(content);
            x400msg.addBodypart(ia5);

            // Add a General Text bodypart
            //BodypartGeneralText gt1 = new BodypartGeneralText(true, "");
            //gt1.setContentFromFile("/etc/hosts");
            //x400msg.addBodypart(gt1);
            // Add a File Transfer bodypart
            //BodypartFTBP ftbp = new BodypartFTBP("/bin/ls");
            //ftbp.setApplicationReferenceOID("2.16.840.1.113694.2.2.1.1");
            //x400msg.addBodypart(ftbp);
            // Set the content type 
            x400msg.setIntParam(X400_att.X400_N_CONTENT_TYPE, 22);

            // If a Message IPM Identifier wasn't assigned, read the value that was calculated
            String ipm_id = x400msg.getMessageIPMIdentifier();

            x400msg.setFrom(from);

            x400msg.setRecipient(true, X400_att.X400_RECIP_PRIMARY, primary1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
//            x400msg.setRecipient(true,X400_att.X400_RECIP_PRIMARY, primary2, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

//            x400msg.setRecipient(true, X400_att.X400_RECIP_CC, cc1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //          x400msg.setRecipient(true,X400_att.X400_RECIP_CC, cc2, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

//            x400msg.setRecipient(true, X400_att.X400_RECIP_BCC, bcc1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //        x400msg.setRecipient(true,X400_att.X400_RECIP_BCC , bcc2, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            

            // x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingPrimaryRecipient(to, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingPrimaryRecipient(to1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingCopyRecipient(cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingCopyRecipient(cc1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingBlindCopyRecipient(bcc,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            // Send the message to the Message Store
            //x400msg.sendMsg(bind_session);
            //x400msg.setTo(primary1,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //x400msg.setTo(primary2,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //x400msg.setCc(cc1,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setCc(cc2,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.sendMsg(bind_session);

            // Unbind cleanly from the Message Store
            // The message was correctly submitted to the Message Store
            // Retrieve the message submission ID (assigned by the MTA) and the submission time
            final String msg_sub_id = x400msg.getMessageIdentifier();
            final String msg_st = x400msg.getSubmissionTime();

            System.out.println("Message submitted.\nMessage Submission ID: "
                    + msg_sub_id + "\nIPM ID: " + ipm_id + "\nSubmission time: " + msg_st);

        } catch (X400APIException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
            System.out.println("Exception code = " + e1.getNativeErrorCode());
//            try {
//                bind_session.unbind();
//            } catch (X400APIException e) {
//            }
//            System.exit(1);
        }
    }

    public static void SendTest() {

        // Since the bind was successful, create a new message object using the 
        // session object that we just created
        X400Msg x400msg = new X400Msg(bind_session);

        // Request an IPN (InterPersonal Notification)
        // These are often known as Read Receipts, and are sent by the receiving user agent
        // when the message is read from the mailbox.
        //
        // In the case below, a notification is requested in both cases, when messages are
        // read and when messages are not read. 
        // If you don't need the positive notification, just remove it. 
        //int ipn_request = X400Msg.IPN_NON_RECEIPT_NOTIFICATION;
        try {
            // Send the message to itself.
            //
            // Request a delivery report (DR), that is, a message generated by the X.400 MTA that contains 
            // information about the delivery of the message. 
            // In this case below, X400Msg.Delivery_Report.DR_DELIVERY_REPORT means that reports will be generated both 
            // when the message is delivered and when it's not delivered.
            // If you don't want positive DRs, use DR_NON_DELIVERY_REPORT or DR_NO_REPORT
            //x400msg.setTo(recipient_or_address, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, ipn_request);

            // Set the subject of the message
            x400msg.setSubject(subject);

            // X.400 messages need a message identifier, that will allow us to correlate 
            // DRs (delivery reports) and IPNs (Inter-Personal Notifications) 
            // This value can be assigned here, or it can be left empty, and a random value
            // will be assigned by the API. This value can be read later with getMessageIPMIdentifier()
            //String msg_id = Long.toString((new Date()).getTime()) + "*";
            //x400msg.setMessageIPMIdentifier(msg_id);
            // Set the MTS Priority
            x400msg.setPriority(X400_Priority.NORMAL_PRIORITY);

            // Set the content, in this case a simple IA5 text bodypart
            //x400msg.setTextBody("This is the body of the test message");
            // Set an optional X.411 Security Label for the message. 
            // There are four ways to add a security label: as a file with a BER encoded byte array,
            // a file with an XML encoded string, an XML encoded String, or a JRSecurityLabel object
            //x400msg.addSecurityLabelAsBER("/opt/isode/share/x400sdk/example/c/x411seclabel.ber");
            //x400msg.addSecurityLabelAsXMLFileName("/opt/isode/share/security-label/example-data/genser-test/lConfidential.xml");
            // Add another File Transfer bodypart
            BodypartIA5Text ia5 = new BodypartIA5Text(content);
            x400msg.addBodypart(ia5);

            // Add a General Text bodypart
            //BodypartGeneralText gt1 = new BodypartGeneralText(true, "");
            //gt1.setContentFromFile("/etc/hosts");
            //x400msg.addBodypart(gt1);
            // Add a File Transfer bodypart
            //BodypartFTBP ftbp = new BodypartFTBP("/bin/ls");
            //ftbp.setApplicationReferenceOID("2.16.840.1.113694.2.2.1.1");
            //x400msg.addBodypart(ftbp);
            // Set the content type 
            x400msg.setIntParam(X400_att.X400_N_CONTENT_TYPE, 22);

            // If a Message IPM Identifier wasn't assigned, read the value that was calculated
            String ipm_id = x400msg.getMessageIPMIdentifier();

            x400msg.setFrom(from);

            String pr1 = "/OU=VVTSOPTA/O=AFTN/PRMD=VIETNAM/ADMD=ICAO/C=XX/";

            x400msg.setRecipient(true, X400_att.X400_RECIP_PRIMARY, pr1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setRecipient(true,X400_att.X400_RECIP_PRIMARY, primary1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);

            // x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingPrimaryRecipient(to, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingPrimaryRecipient(to1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingCopyRecipient(cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingCopyRecipient(cc1, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(cc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setBcc(bcc, X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setIPMHeadingBlindCopyRecipient(bcc,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            // Send the message to the Message Store
            //x400msg.sendMsg(bind_session);
            //x400msg.setTo(primary1,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //x400msg.setTo(primary2,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);            
            //x400msg.setCc(cc1,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            //x400msg.setCc(cc2,X400Msg.DR_Request.DR_NON_DELIVERY_REPORT, X400Msg.IPN_NON_RECEIPT_NOTIFICATION);
            x400msg.sendMsg(bind_session);

            // Unbind cleanly from the Message Store
            // The message was correctly submitted to the Message Store
            // Retrieve the message submission ID (assigned by the MTA) and the submission time
            final String msg_sub_id = x400msg.getMessageIdentifier();
            final String msg_st = x400msg.getSubmissionTime();

            System.out.println("Message submitted.\nMessage Submission ID: "
                    + msg_sub_id + "\nIPM ID: " + ipm_id + "\nSubmission time: " + msg_st);

        } catch (X400APIException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
            System.out.println("Exception code = " + e1.getNativeErrorCode());
//            try {
//                bind_session.unbind();
//            } catch (X400APIException e) {
//            }
//            System.exit(1);
        }

    }

//    private void buildContentCCandBCC(X400Msg msMessage, String content,String subject  ) throws X400APIException {
////        setStrParam(msMessage, X400_att.X400_S_SUBJECT, outbox.getSubject());
//        msMessage.setSubject(subject);
//////        setIntParam(msMessage, X400_att.X400_N_NUM_ATTACHMENTS, 1);
//////        setStrParam(msMessage, X400_att.X400_S_IPM_IDENTIFIER, MSUtil.generateIpmId(outbox.getOrigin()));
////        msMessage.setMessageIPMIdentifier(MSUtil.generateIpmId(outbox.getOrigin()));
////        setIntParam(msMessage, X400_att.X400_N_IMPORTANCE, DefaultMessageProperty.context.getImportance());
////        setIntParam(msMessage, X400_att.X400_N_SENSITIVITY, DefaultMessageProperty.context.getSensitivity());
////        if (outbox.getAtsOhi() != null && outbox.getAtsOhi() != null) {
////            setStrParam(msMessage, AMHS_att.ATS_S_OPTIONAL_HEADING_INFO, outbox.getAtsOhi());             
////        }
//        if (outbox.getAtsPriority() != null && outbox.getAtsFilingTime() != null) {
////            setStrParam(msMessage, AMHS_att.ATS_S_PRIORITY_INDICATOR, outbox.getAtsPriority());
////            setStrParam(msMessage, AMHS_att.ATS_S_FILING_TIME, outbox.getAtsFilingTime());
//            setStrParam(msMessage, AMHS_att.ATS_S_TEXT, content);
////            msMessage.setTextBody(outbox.getContent());
////            setIntParam(msMessage, AMHS_att.ATS_EOH_MODE, AMHS_att.ATS_EOH_MODE_NONE);
////            setIntParam(msMessage, AMHS_att.ATS_N_EXTENDED, outbox.getAtsExtention() ? 1 : 0);
//        } else {
//            setStrParam(msMessage, X400_att.X400_T_IA5TEXT, outbox.getContent());
////            msMessage.setTextBody(outbox.getContent());
//        }
//        if (1) {
//            msMessage.setIntParam(AMHS_att.ATS_N_EXTENDED, 1);
////            msMessage.setStringparam(X400_att.X400_S_PRECEDENCE_POLICY_ID, "1.3.27.8.0.0"); 
//        } else {
//            msMessage.setIntParam(AMHS_att.ATS_N_EXTENDED, 0);
////            com.isode.x400api.X400ms.x400_ms_msgaddintparam(msMessage, AMHS_att.ATS_EOH_MODE, AMHS_att.ATS_EOH_MODE_NONE); 
//        }
//    }
    private void setIntParam(X400Msg ms, int attribute, Integer value) {
        if (value == null) {
            return;
        }
        try {
            ms.setIntParam(attribute, value);
        } catch (X400APIException ex) {
            Logger.getLogger(SendX400Mail_1.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
    }

    private void setStrParam(X400Msg ms, int attribute, String value) {
        if (value == null) {
            return;
        }
        try {
            ms.setStringparam(attribute, value);
        } catch (X400APIException ex) {
            Logger.getLogger(SendX400Mail_1.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }

    }

    public static void main(String[] args) {
        System.out.println("Connecting to the P7 Message Store... ");

        // Create a new P7 bind session object with the session values necessary for the bind
        connection = new P7BindSession(p7_message_store_presentation_address,
                p7_user_or_address, p7_user_password);

        // Bind to the P7 Message Store
        try {
            connection.bind();
        } catch (X400APIException e) {
            e.printStackTrace();
            System.exit(1);
        }

        bind_session = connection;

        Send();
        SendBCC(bcc2);
        SendBCC(bcc1);
        SendTOCC();

        // Kiem tra BCC tren 1 dien van
        //Send();
        // Kiem tra dien le
        //SendTest();
        try {

            bind_session.unbind();
        } catch (X400APIException ex) {
            Logger.getLogger(SendX400Mail_1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
